site_name: Tài liệu kỹ thuật (Bản dịch tiếng Việt)
site_description: Tổng hợp các bản dịch tiếng Việt của tài liệu kỹ thuật mã nguồn mở
docs_dir: docs

theme:
  name: material
  language: vi
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Chuyển sang chế độ tối
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Chuyển sang chế độ sáng
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
    - toc.follow

plugins:
  - search:
      lang:
        - vi
        - en
  - awesome-nav

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
